FROM python:3.8-slim-buster

ADD . /flask-deploy

WORKDIR /flask-deploy

RUN pip3 install -r requirements.txt
RUN pip3 install gunicorn[gevent]

EXPOSE 5000

CMD gunicorn --worker-class gevent --workers 4 --bind 0.0.0.0:5000 wsgi:app --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info